Messages
ghosts-network/messages pull request #1
Opened 2022-04-13 23:09 UTC by Sekir0

2022-04-15 15:12 UTC, Boberneprotiv requested changes
Add seperate controller for messages

2022-04-15 15:12 UTC, volodymyr-borodin commented on tests/GhostNetwork.Messages.UnitTests/UnitTest1.cs
> +
Empty file

2022-04-15 15:12 UTC, volodymyr-borodin commented on GhostNetwork.Messages/Chat.cs
> +    public Guid Id { get; }
Please add Name property for chat. This should be required field

2022-04-15 15:12 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/ChatController.cs
> +            return Ok(existChats);
Returning just chat guids not really useful. I think it's better to return chat objects (id, name, participants?)

2022-04-15 15:12 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/ChatController.cs
> +        public async Task<ActionResult<Guid>> CreateNewChatAsync([FromBody] IEnumerable<Guid> users)
Use object for body with Participants and Name properties

2022-04-15 15:12 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/ChatController.cs
> +        /// Get chat history by chat id
why "history" not messages?

2022-04-15 15:13 UTC, Boberneprotiv commented
@Sekir0 PR is pretty big so we might have several rounds of changes request

2022-04-15 16:14 UTC, Sekir0 commented
@Boberneprotiv Yup

2022-04-17 09:28 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/MessageController.cs
> +        [FromQuery, Range(0, int.MaxValue)] int skip,
I 100% sure here we need cursor pagination

2022-04-17 09:31 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/MessageController.cs
> +            return BadRequest(result.Errors);
We are using rfc7807 (Problem details) as bad request response all over services
See example at: https://github.com/ghosts-network/content/blob/master/GhostNetwork.Content.Api/Helpers/DomainResultExtensions.cs

2022-04-17 09:47 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/MessagesController.cs
> +        var (result, message) = await messageService.SendAsync(chatId, model.SenderId, model.Message);
There is no validation that SenderId should be one of participants

2022-04-17 09:48 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/ChatsController.cs
> +            return BadRequest(result.Errors);
We use rfc7807 as BadRequest response
See more here: https://github.com/ghosts-network/content/blob/master/GhostNetwork.Content.Api/Helpers/DomainResultExtensions.cs

2022-04-17 09:48 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/ChatsController.cs
> +            return BadRequest(result.Errors);
Same as for create

2022-04-17 09:59 UTC, Boberneprotiv requested changes
I've made small style changes. Please review comments and we will proceed

2022-04-19 08:53 UTC, Sekir0 commented
I think need save UserInfo {Id, Name, ProfileImage} instead just user id

2022-04-19 09:14 UTC, Boberneprotiv commented
> I think need to save UserInfo {Id, Name, ProfileImage} instead just user id. For each message

You are right. The same as for content
https://github.com/ghosts-network/content/blob/master/GhostNetwork.Content/UserInfo.cs

2022-04-20 10:30 UTC, Boberneprotiv commented on GhostNetwork.Messages/Messages/IMessagesService.cs
> +        var participantsCheck = await messageStorage.ParticipantsCheckAsync(author.Id);
I think this validation should be wraped to IValidator

2022-04-20 10:33 UTC, Boberneprotiv commented on GhostNetwork.Messages/Chats/Chat.cs
> +    public Chat(Guid id, string name, List<Guid> users)
I think it will be more useful to have UserInfo for users property

2022-04-20 10:34 UTC, Boberneprotiv commented on GhostNetwork.Messages/Chats/Chat.cs
> +    public List<Guid> Users { get; private set; }
Please rename to Participants

2022-04-20 10:36 UTC, Boberneprotiv commented
I see that some of requests were resolved, so I've added new

2022-04-23 17:45 UTC, Boberneprotiv requested changes
Failed tests

2022-04-23 17:46 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/ChatsController.cs
> +            return BadRequest();
Add details witch Participants not found

2022-04-23 17:47 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/ChatsController.cs
> +        foreach (var userId in model.Participants)
If any participants not found request should be invalid

2022-04-23 17:48 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Helpers/ProfilesApiUserProvider.cs
> +            var result = await profilesApi.GetByIdAsync(guid);
There is SearchByIdsAsync to check all participants

2022-04-23 17:49 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/ChatsController.cs
> +            var participant = await userProvider.GetByIdAsync(userId);
There is SearchByIdsAsync to check all participants with one http request

2022-04-23 17:50 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/ChatsController.cs
> +            return BadRequest();
Add details

2022-04-23 17:51 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/MessagesController.cs
> +            return BadRequest(result.ToProblemDetails());
Add details

2022-04-23 17:51 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/MessagesController.cs
> +            return BadRequest();
Add details

2022-04-23 17:52 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Controllers/ChatsController.cs
> +    /// <response code="204">Smt went wrong</response>
Wrong response code

2022-05-01 10:03 UTC, Boberneprotiv requested changes
Trying to post message to not existing chat I receive 500 response code. Should be 400

2022-05-01 10:05 UTC, Boberneprotiv requested changes
Internal server error while trying create char without participants. I believe there should be validation

{
  "name": "string"
}

2022-05-01 10:16 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Helpers/ProfilesApiUserProvider.cs
> +            Console.WriteLine(ex);
ILogger should be used

2022-05-01 10:16 UTC, Boberneprotiv commented on GhostNetwork.Messages.Api/Helpers/ProfilesApiUserProvider.cs
> +            return null;
Never null should be returned instead of empty array

2022-05-02 17:46 UTC, Boberneprotiv requested changes
Internal server error while trying to update unexacting chat

2022-05-11 17:21 UTC, merged